version: "3.9"

services: 
  server:
    container_name: server
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/dictionary
      - LANGCHAIN_TRACING_V2=${LANGSMITH_TRACING}
      - LANGCHAIN_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGSMITH_API_KEY}
    env_file:
      - .env
    volumes:
      - ./:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  db:
    container_name: db
    image: pgvector/pgvector:pg16  
    restart: always
    environment:
      - POSTGRES_DB=dictionary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
