services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 30s
  db:
    container_name: db
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_DB=dictionary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"               
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dictionary"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    container_name: server
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/dictionary
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=gemma3n  
      - LANGCHAIN_TRACING_V2=${LANGSMITH_TRACING}
      - LANGCHAIN_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGSMITH_API_KEY}
    env_file:
      - .env
    volumes:
      - ./:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  db-data:
  ollama: