"""schema fixes

Revision ID: 24c4c27d30c1
Revises: 28cf33477fea
Create Date: 2025-08-23 08:46:49.948655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c4c27d30c1'
down_revision: Union[str, Sequence[str], None] = '28cf33477fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('definitions_original_text_id_fkey'), 'definitions', type_='foreignkey')
    op.drop_column('definitions', 'original_text_id')
    op.alter_column('texts', 'learning_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('texts', 'learning_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('definitions', sa.Column('original_text_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('definitions_original_text_id_fkey'), 'definitions', 'texts', ['original_text_id'], ['id'])
    # ### end Alembic commands ###
