"""update

Revision ID: 286355e72afb
Revises: 3a0fc290d49a
Create Date: 2025-08-12 19:43:46.358575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286355e72afb'
down_revision: Union[str, Sequence[str], None] = '3a0fc290d49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('learning_profiles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint('unique_translation_pair', 'word_translations', ['word_id', 'translation_id'])
    op.drop_constraint(op.f('word_translations_word_id_fkey'), 'word_translations', type_='foreignkey')
    op.drop_constraint(op.f('word_translations_translation_id_fkey'), 'word_translations', type_='foreignkey')
    op.create_foreign_key(None, 'word_translations', 'words', ['word_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'word_translations', 'words', ['translation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('unique_user_word_per_language', 'words', ['lemma', 'language_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_word_per_language', 'words', type_='unique')
    op.drop_constraint(None, 'word_translations', type_='foreignkey')
    op.drop_constraint(None, 'word_translations', type_='foreignkey')
    op.create_foreign_key(op.f('word_translations_translation_id_fkey'), 'word_translations', 'words', ['translation_id'], ['id'])
    op.create_foreign_key(op.f('word_translations_word_id_fkey'), 'word_translations', 'words', ['word_id'], ['id'])
    op.drop_constraint('unique_translation_pair', 'word_translations', type_='unique')
    op.drop_column('learning_profiles', 'is_active')
    op.drop_column('dictionaries', 'notes')
    # ### end Alembic commands ###
