"""user disabled fix

Revision ID: 4e9c102c144e
Revises: 83bf9aa1f62f
Create Date: 2025-08-23 10:40:01.699514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9c102c144e'
down_revision: Union[str, Sequence[str], None] = '83bf9aa1f62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
