"""bugs fix

Revision ID: 5c0d4291734c
Revises: 6bceb075302e
Create Date: 2025-08-16 09:00:09.503533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0d4291734c'
down_revision: Union[str, Sequence[str], None] = '6bceb075302e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('dictionary_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'translations', 'dictionaries', ['dictionary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_column('translations', 'dictionary_id')
    # ### end Alembic commands ###
