"""schema change

Revision ID: 71e7d4e3ae18
Revises: 925fa225f882
Create Date: 2025-08-19 14:42:55.501026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e7d4e3ae18'
down_revision: Union[str, Sequence[str], None] = '925fa225f882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dictionaries_original_text_id_fkey'), 'dictionaries', type_='foreignkey')
    op.drop_column('dictionaries', 'original_text_id')
    op.add_column('texts', sa.Column('dictionary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'texts', 'dictionaries', ['dictionary_id'], ['id'])
    op.alter_column('user_word_progress', 'learning_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_word_progress', 'learning_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.drop_column('texts', 'dictionary_id')
    op.add_column('dictionaries', sa.Column('original_text_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('dictionaries_original_text_id_fkey'), 'dictionaries', 'texts', ['original_text_id'], ['id'])
    # ### end Alembic commands ###
