"""relationship fix

Revision ID: f17af98ec0aa
Revises: 5c0d4291734c
Create Date: 2025-08-16 09:02:19.318129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f17af98ec0aa'
down_revision: Union[str, Sequence[str], None] = '5c0d4291734c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_word_progress_id'), table_name='user_word_progress')
    op.drop_table('user_word_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_word_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learning_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proficiency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_reviewed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_review_due', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['learning_profile_id'], ['learning_profiles.id'], name=op.f('user_word_progress_learning_profile_id_fkey')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('user_word_progress_word_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_word_progress_pkey'))
    )
    op.create_index(op.f('ix_user_word_progress_id'), 'user_word_progress', ['id'], unique=False)
    # ### end Alembic commands ###
